version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION=pgsql
      DB_HOST=host.docker.internal
      DB_PORT=5432
      DB_DATABASE=mydb
      DB_USERNAME=emerson
      DB_PASSWORD=secret123
