version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=mydb
      - DB_USER=emerson
      - DB_PASSWORD=secret123
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
