version: "3.9"

services:
  node:
    build: .
    container_name: node_app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://emerson:secret123@host.docker.internal:27017
      - PG_URI=postgresql://emerson:secret123@host.docker.internal:5432/mydb
